### ISSUE TITLE
Problem with including Google Map to project on this boilerplate

### ISSUE THREAD

**Issue by s3c0nDD** [yeoman/generator-webapp#644]
So, I choosed this boilerplate and i really like it. 
But i have a problem with including even simpliest Google Map as here: https://developers.google.com/maps/documentation/javascript/examples/map-simple

##### In my html i have: 
```html
<section class="map">
  <h3 class="map-header">WHERE CAN I FIND MORE INFORMATION</h3>
  <div class="map-container">
    <div id="#map"></div>
  </div>
</section>
```
##### and in my SCSS i have: 
```scss
 .map {
  &-header {
    // not important
  }
  &-container {`
      width: 100%;
      height: 199px;
      background-color: grey;
      #map {
        height: 100%;
      } // from #map
  } // from &-container
} // from .map
```
##### I added a script 
`<script src="https://maps.googleapis.com/maps/api/js?key=*myKeyHere*" type="text/javascript"></script>` 
just before 
`<script src="scripts/main.js"></script>` in index.html

##### Then i added:
`let map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 8
});`

------------------
#### Error from console is
`Uncaught TypeError: Cannot read property 'firstChild' of null`
`at Object._.vg (js?key=*myKeyHere*:87)`
`at new Ag (js?key=*myKeyHere*:87)`
 `at main.js [sm]:4`

------------------
### Question / Issue is: how can i properly add a google map to the project?
